-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PageVersions/db/page_version.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_version (
  pv_rev INTEGER UNSIGNED NOT NULL,
  pv_version VARCHAR(255) NOT NULL,
  pv_wiki_id VARCHAR(255) NOT NULL,
  pv_page VARCHAR(255) NOT NULL,
  pv_timestamp BLOB NOT NULL,
  pv_actor INTEGER UNSIGNED DEFAULT NULL,
  pv_comment VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY(pv_rev, pv_version, pv_wiki_id)
);
